remote_theme: artemsheludko/flexible-jekyll
plugins:
  - jekyll-remote-theme

title: Sweet-Twixie’s Site
description: My site with Flexible-Jekyll theme
show_downloads: false  # optional, remove if unsupported


